name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  firebase_core: ^2.24.2  # Latest stable
  firebase_auth: ^4.17.4  # Latest stable
  cloud_firestore: ^4.15.5 # Latest stable
  firebase_auth_web: any  # Allow automatic version updates

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
